[platformio]
default_envs = esp32dev

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
src_dir = firmware/esp32_ac_ir_hub
lib_deps =
  crankyoldgit/IRremoteESP8266@^2.9.0
